---
title: "Proposal for r-spatial/discuss repo PROJ and geometry invalidity issues"
author: "Roger Bivand"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 2
theme: united
bibliography: bus463.bib
link-citations: yes
---

## Outcomes of OpenGeoHub summer school session 

In discussion during and around the session, it was suggested that [issues in R-spatial/discuss](https://github.com/r-spatial/discuss) be used as a forum for collating points with regard to the upstream change problems raised. The two topics are transition to late-binding transformation pipelines in PROJ and changes un GDAL drivers and GEOS with regard to tightening of vector geometry validity requirements.

This document is a place to draft the issue texts to bring in overviews of the two (more?) topics. Please provide PRs to this document until we feel that we are ready to publish the R-spatial/discuss issues.

When we publish the issues, how should we try to bring in users whose workflows will be impacted by changes related to upstream software and made in R packages with many reverse dependencies? Please comment: R-sig-geo, twitter, other channels?


## PROJ 6 CRS handling changes impact workflows using +datum= (and other fun)

PUBLISHED AS https://github.com/r-spatial/discuss/issues/28 and https://github.com/r-spatial/sf/issues/1146 2019-09-11.

[Ongoing changes](https://proj.org/development/migration.html) in the representation of coordinate reference systems in the [PROJ](https://proj.org), external software used by **sf**, **sp** and other R packages, will impact R packages and workflows using these packages. In particular, the changes affect transformation between coordinate reference systems, as for example shown in [this presentation](https://rsbivand.github.io/geostat19_talk/geostat_bivand_19.html) at the OpenGeoHub Summer School 2019.

- Invite users/developers to contribute cases

- Add other examples and links, also from other geospatial software.

Notes from [Spatialite](https://www.gaia-gis.it/fossil/libspatialite/wiki?name=PROJ.6)

PROJ wiki [proj.h adoption status](https://github.com/OSGeo/PROJ/wiki/proj.h-adoption-status)

[PostGIS blog posting](https://info.crunchydata.com/blog/waiting-for-postgis-3-st_transform-and-proj6)

[GRASS-dev thread](https://lists.osgeo.org/pipermail/grass-dev/2019-September/093150.html) and [PR](https://github.com/OSGeo/grass/pull/118)

**cartography** [CRS issues](https://github.com/riatelab/cartography/issues/54)

**geojsonio** [geojsonio seems vulnerable to PROJ 6](https://github.com/ropensci/geojsonio/issues/148)

**MODIS** [getTile() sp subset or raster::crop issues with PROJ 6.1 and GDAL 3.0](https://github.com/MatMatt/MODIS/issues/71)

**MODIStsp** [PROJ 6 failures in MODIStsp](https://github.com/ropensci/MODIStsp/issues/167)

**rangeMapper** [PROJ 6 failures in rangeMapper](https://github.com/mpio-be/rangeMapper/issues/5)

**rdefra** [PROJ 6 failures in rdefra](https://github.com/ropensci/rdefra/issues/9)

**rnrfa** [PROJ 6 failures in rnfra](https://github.com/cvitolo/rnrfa/issues/15)

**rshapemapper** [PROJ 6 problems?](https://github.com/ateucher/rmapshaper/issues/88)

Incomplete list of packages with CRAN issues after PROJ 6.2.0 installed on some test machines:

https://cran.r-project.org/web/checks/check_results_foieGras.html
https://cran.r-project.org/web/checks/check_results_plotKML.html
https://cran.r-project.org/web/checks/check_results_rangeMapper.html
https://cran.r-project.org/web/checks/check_results_rnrfa.html
https://cran.r-project.org/web/checks/check_results_sf.html
https://cran.r-project.org/web/checks/check_results_vapour.html


- Provide recommendations for checking/testing PROJ versions in use and expected transformation outcomes


## Vector geometry invalidity/frailty exposed as unrelated bugs fixed in GEOS and GDAL

PUBLISHED AS https://github.com/r-spatial/discuss/issues/27 2019-09-11.

Ongoing changes in vector geometry validity handling in GEOS and GDAL drivers used in R packages **sf**, **rgdal** and **rgeos** have led to unexpected changes or failures in R workflows and packages using these packages. Operations which previously appeared to succeed now fail, either noisily (good) or silently (bad).

- Invite users/developers to contribute cases

- Add other examples and links.

Shapefile affected: [ESRI Shapefile driver not roundtripping in edge case](https://github.com/r-spatial/sf/issues/1130)

Intersection affected: [GEOS 3.7.1 to 3.7.2 tightening of validity needed for operations](https://github.com/r-spatial/sf/issues/1121)

Plotting in **tmap** affected: [tm_graticules() does not work for some cases](https://github.com/mtennekes/tmap/issues/333)

**lidR** [problem with class inheritance](https://github.com/Jean-Romain/lidR/issues/268)

**MODIS** [getTile() sp subset or raster::crop issues with PROJ 6.1 and GDAL 3.0](https://github.com/MatMatt/MODIS/issues/71)

**inlmisc** [Possible GEOS version vulnerability (3.7.2)](https://github.com/USGS-R/inlmisc/issues/106)

- Provide recommendations for checking/testing driver/GEOS versions in use and expected geometry handling outcomes



